In [11]:
import numpy as np
from scipy.sparse.linalg import svds

# Define the matrix R
R = np.array([[1, 0, 1, 0],
              [0, 1, 0, 1],
              [1, 1, 0, 0]], dtype=np.float32)

# Performs matrix factorisation of the original user item matrix
u, s, vt = svds(R, k=2)  # k is number of factors
s = np.diag(s)
print(u.shape, vt.shape, s.shape)


(3, 2) (2, 4) (2, 2)


In [13]:
# Reconstruct R
R_reconstructed = np.dot(u, np.dot(s, vt))
print(R_reconstructed)

[[ 1.1035535   0.10355331  0.75000006 -0.25000006]
 [ 0.10355344  1.1035535  -0.24999996  0.75      ]
 [ 0.8535535   0.85355335  0.3535534   0.35355332]]


In [22]:
def normalize_matrix(X):
    # Find the minimum and maximum values in the matrix
    X_min = X.min()
    X_max = X.max()
    
    # Apply the normalization formula
    X_normalized = (X - X_min) / (X_max - X_min)
    
    return X_normalized

np.set_printoptions(precision=2, suppress=True)
print(normalize_matrix(R_reconstructed))

[[1.   0.26 0.74 0.  ]
 [0.26 1.   0.   0.74]
 [0.82 0.82 0.45 0.45]]
