In [1]:
import pandas as pd

In [2]:
df_associate = pd.read_csv("../data/track_playlist_association.csv")
df = pd.read_csv("../data/matched_songs.csv")

In [3]:
df.head()

Unnamed: 0  pos        artist_name                             track_uri  \
0           0    1     Britney Spears  spotify:track:6I9VzXrHxO9rA9A5euc8Ak   
1           0    3  Justin Timberlake  spotify:track:1AWQoqb9bSvzTjaLralEkT   
2           0    8    Destiny's Child  spotify:track:7H6ev70Weq6DdpZyyTmUXk   
3           0    9            OutKast  spotify:track:2PpruBYCo4H7WOBJ7Q2EwM   
4           0   19    Destiny's Child  spotify:track:4pmc2AxSEq6g7hPVlJCPyP   

                              artist_uri                      track_name  \
0  spotify:artist:26dSoYclwsYLMAKD3tpOr4                           Toxic   
1  spotify:artist:31TPClRtHm23RisEBtV3X7                  Rock Your Body   
2  spotify:artist:1Y8cdNmUJH7yBTd9yOvr5i                     Say My Name   
3  spotify:artist:1G9G7WwrXka3Z1r7aIDjI7  Hey Ya! - Radio Mix / Club Mix   
4  spotify:artist:1Y8cdNmUJH7yBTd9yOvr5i                Jumpin', Jumpin'   

                              album_uri  duration_ms_x  \
0  spotify:album:0z7pVBGOD7HCIB7S8eLkLI         198800   
1  spotify:album:6QPkyl04rXwTGlGlcYaRoW         267266   
2  spotify:album:283NWqNsCA9GwVHrJk59CG         271333   
3  spotify:album:1UsmQ3bpJTyK6ygoOOjG1r         235213   
4  spotify:album:283NWqNsCA9GwVHrJk59CG         230200   

                    album_name                      id  ... speechiness  \
0                  In The Zone  6I9VzXrHxO9rA9A5euc8Ak  ...      0.1140   
1                    Justified  1AWQoqb9bSvzTjaLralEkT  ...      0.1400   
2    The Writing's On The Wall  7H6ev70Weq6DdpZyyTmUXk  ...      0.1020   
3  Speakerboxxx/The Love Below  2PpruBYCo4H7WOBJ7Q2EwM  ...      0.0664   
4    The Writing's On The Wall  4pmc2AxSEq6g7hPVlJCPyP  ...      0.0567   

  acousticness instrumentalness liveness valence    tempo  duration_ms_y  \
0      0.02490         0.025000   0.2420   0.924  143.040         198800   
1      0.20200         0.000234   0.0521   0.818  100.972         267267   
2      0.27300         0.000000   0.1490   0.734  138.009         271333   
3      0.10300         0.000532   0.1740   0.965   79.526         235213   
4      0.00543         0.001570   0.0537   0.683   88.997         230200   

   time_signature  year  release_date  
0             4.0  2003    2003-11-13  
1             4.0  2002    2002-11-04  
2             4.0  1999    1999-07-27  
3             4.0  2003          2003  
4             4.0  1999    1999-07-27  

[5 rows x 33 columns]

In [4]:
df_associate
print(df_associate)

                                    track_uri  playlist_id
0        spotify:track:6I9VzXrHxO9rA9A5euc8Ak            0
1        spotify:track:6I9VzXrHxO9rA9A5euc8Ak       884736
2        spotify:track:6I9VzXrHxO9rA9A5euc8Ak       884738
3        spotify:track:6I9VzXrHxO9rA9A5euc8Ak        32775
4        spotify:track:6I9VzXrHxO9rA9A5euc8Ak        32777
...                                       ...          ...
8171516  spotify:track:38Zq6XbsyIcwI0Kn1ikPlV       999829
8171517  spotify:track:68nYzKdsOUiiVAuyAc5y3U       999829
8171518  spotify:track:2U7FCJK3m012zjvPlAw4PK       999870
8171519  spotify:track:1HkPxeUaQwIFIbYCRq9nyK       999887
8171520  spotify:track:533lw7eUjXE5ZbajU8L4H6       999935

[8171521 rows x 2 columns]


In [5]:
def get_tracks_by_playlist(df, playlist_id):
    """
    Retrieve all track URIs associated with a specific playlist ID.
    
    Parameters:
        df (pd.DataFrame): The DataFrame containing 'track_uri' and 'playlist_id'.
        playlist_id (int): The ID of the playlist to filter tracks for.
    
    Returns:
        list: A list of track URIs associated with the given playlist ID.
    """
    # Filter the DataFrame and retrieve the track URIs
    return df[df['playlist_id'] == playlist_id]['track_uri']

In [6]:
def get_number_of_playlists(df):
    return df['playlist_id'].nunique()
def get_number_of_songs_in_playlist(df: pd.DataFrame, playlist_id: int) -> int:
    """
    Get the number of songs in a specific playlist.

    :param df: The DataFrame containing 'track_uri' and 'playlist_id'.
    :param playlist_id: The playlist ID to count songs for.
    :return: The number of songs in the playlist.
    """
    return df[df['playlist_id'] == playlist_id].shape[0]

In [7]:
df_sorted = df_associate.sort_values(by='playlist_id', ascending=True)

print(get_number_of_playlists(df_associate))

887060


In [8]:
print(get_tracks_by_playlist(df_associate, 0))
print(get_number_of_songs_in_playlist(df_associate, 0))

0        spotify:track:6I9VzXrHxO9rA9A5euc8Ak
12951    spotify:track:1AWQoqb9bSvzTjaLralEkT
21938    spotify:track:7H6ev70Weq6DdpZyyTmUXk
35384    spotify:track:2PpruBYCo4H7WOBJ7Q2EwM
56628    spotify:track:4pmc2AxSEq6g7hPVlJCPyP
63151    spotify:track:19Js5ypV6JKn4DMExHQbGc
Name: track_uri, dtype: object
6


In [9]:
def get_tracks_by_playlist(df_playlist: pd.DataFrame, df_tracks: pd.DataFrame, playlist_id: int) -> pd.DataFrame:
    """
    Get detailed track information for a specific playlist ID.

    :param df_playlist: DataFrame containing 'track_uri' and 'playlist_id'.
    :param df_tracks: DataFrame containing detailed track information.
    :param playlist_id: The playlist ID to filter tracks for.
    :return: A DataFrame with detailed track information for the playlist.
    """
    # Filter the playlist DataFrame for the specified playlist ID
    filtered_playlist = df_playlist[df_playlist['playlist_id'] == playlist_id]

    # Merge with the track information DataFrame on 'track_uri'
    return filtered_playlist.merge(df_tracks, on='track_uri', how='inner')

In [10]:
get_tracks_by_playlist(df_associate, df, 2)

track_uri  playlist_id  Unnamed: 0  pos  \
0  spotify:track:73szhI6oOawKlv6AxgHIS8            2           2   37   
1  spotify:track:7uzib3dSSwgUwcD3z0k3bR            2           2   38   
2  spotify:track:1Zyd6zQnC6XIIzmg3hP7Ot            2           2   40   

  artist_name                             artist_uri            track_name  \
0     BIGBANG  spotify:artist:4Kxlr1PRlDKEB0ekOCyHgX            LAST DANCE   
1     BIGBANG  spotify:artist:4Kxlr1PRlDKEB0ekOCyHgX               FXXK IT   
2   BLACKPINK  spotify:artist:41MozSoPIsD1dJM0CLPjZF  As If It's Your Last   

                              album_uri  duration_ms_x            album_name  \
0  spotify:album:1q8h2HdED1cmgJVo8lEBME         279719                  MADE   
1  spotify:album:1q8h2HdED1cmgJVo8lEBME         231810                  MADE   
2  spotify:album:6IzQb2kLydYNfzmKXvmndX         213264  As If It's Your Last   

   ... speechiness acousticness instrumentalness liveness valence    tempo  \
0  ...      0.0606       0.4670              0.0   0.3230   0.289  143.889   
1  ...      0.1070       0.1520              0.0   0.2760   0.587   90.026   
2  ...      0.0816       0.0688              0.0   0.0759   0.450  125.034   

   duration_ms_y  time_signature  year  release_date  
0         279719             4.0  2016    2016-12-13  
1         231811             4.0  2016    2016-12-13  
2         213264             4.0  2017    2017-06-22  

[3 rows x 34 columns]

In [11]:
from adv_ml_music_recommendation.util.data_functions import get_interacted_tracks

# Get interacted and non-interacted tracks for playlist ID 0
tracks_interacted, tracks_not_interacted = get_interacted_tracks(df_associate, df, 0)
tracks_not_interacted


Unnamed: 0  pos          artist_name  \
0                1    0             Survivor   
1                1    9      Leslie Odom Jr.   
2                1   10  Christopher Jackson   
3                1   11      Leslie Odom Jr.   
4                1   12   Lin-Manuel Miranda   
...            ...  ...                  ...   
134701         829   24          The Outlaws   
134702         829  131          The Outlaws   
134703         870   69      History Invades   
134704         887    5            Limi-T 21   
134705         935   32          Rod Stewart   

                                   track_uri  \
0       spotify:track:2HHtWyy5CgaQbC7XSoOb0e   
1       spotify:track:2TK2KSrzXD6W01qjXVjNGh   
2       spotify:track:3nJYcY9yvKP8Oi2Ml8brXt   
3       spotify:track:4TTV7EcfroSLWzXRY6gLv6   
4       spotify:track:4cxvludVmQxryrnx1m9FqL   
...                                      ...   
134701  spotify:track:38Zq6XbsyIcwI0Kn1ikPlV   
134702  spotify:track:68nYzKdsOUiiVAuyAc5y3U   
134703  spotify:track:2U7FCJK3m012zjvPlAw4PK   
134704  spotify:track:1HkPxeUaQwIFIbYCRq9nyK   
134705  spotify:track:533lw7eUjXE5ZbajU8L4H6   

                                   artist_uri  \
0       spotify:artist:26bcq2nyj5GB7uRr558iQg   
1       spotify:artist:3cR4rhS2hBWqI7rJEBacvN   
2       spotify:artist:6sLwRSXSUF5JTUnQaFenyj   
3       spotify:artist:3cR4rhS2hBWqI7rJEBacvN   
4       spotify:artist:4aXXDj9aZnlshx7mzj3W1N   
...                                       ...   
134701  spotify:artist:72JEwd3EjDEwTLypkFYJn9   
134702  spotify:artist:72JEwd3EjDEwTLypkFYJn9   
134703  spotify:artist:0uDgv6be8MjRPqZ1v7WiZa   
134704  spotify:artist:5j8Q0VC4Be4yhcQ1tf8Sh7   
134705  spotify:artist:2y8Jo9CKhJvtfeKOsYzRdT   

                                               track_name  \
0                                        Eye of the Tiger   
1                               The Room Where It Happens   
2                                          Right Hand Man   
3                                      Alexander Hamilton   
4                                                 My Shot   
...                                                   ...   
134701                                       Freedom Walk   
134702                                         Dirty City   
134703                              Its All Over (Ending)   
134704                   Una Despedida (Tropical version)   
134705  Standin' In the Shadows of Love - 2008 Remaste...   

                                   album_uri  duration_ms_x  \
0       spotify:album:4PT9VulQaQP6XR1xBI2x1W         243773   
1       spotify:album:1kCHru7uhxBUdzkm4gzRQc         318214   
2       spotify:album:1kCHru7uhxBUdzkm4gzRQc         321696   
3       spotify:album:1kCHru7uhxBUdzkm4gzRQc         236737   
4       spotify:album:1kCHru7uhxBUdzkm4gzRQc         333154   
...                                      ...            ...   
134701  spotify:album:7IHvSlqB21xW52rQcLez8a         346880   
134702  spotify:album:7Lu3iMeH7KWrbqnXHfgEgU         327426   
134703  spotify:album:4774uhbJcNqmK2PDpTKC92         141626   
134704  spotify:album:3D2qTNwjpvoK1d4t53BjaT         219066   
134705  spotify:album:38tXOrjXUUfQWWV2DRwMio         268266   

                                album_name                      id  ...  \
0                         Eye Of The Tiger  2HHtWyy5CgaQbC7XSoOb0e  ...   
1                                 Hamilton  2TK2KSrzXD6W01qjXVjNGh  ...   
2                                 Hamilton  3nJYcY9yvKP8Oi2Ml8brXt  ...   
3                                 Hamilton  4TTV7EcfroSLWzXRY6gLv6  ...   
4                                 Hamilton  4cxvludVmQxryrnx1m9FqL  ...   
...                                    ...                     ...  ...   
134701                        Ghost Riders  38Zq6XbsyIcwI0Kn1ikPlV  ...   
134702                      Playin' to Win  68nYzKdsOUiiVAuyAc5y3U  ...   
134703  The Structure Of A Precise Fashion  2U7FCJK3m012zjvPlAw4PK  ...   
134704                   

In [12]:
from adv_ml_music_recommendation.util.data_functions import create_interaction_matrix, create_sparse_interaction_matrix

df_a = create_sparse_interaction_matrix(df_associate, df)
df_a

<887060x134712 sparse array of type '<class 'numpy.float64'>'
	with 8171521 stored elements in Compressed Sparse Row format>

In [13]:
print(get_number_of_playlists(df_associate))
print(len(df))

887060
134712


In [14]:
print(df_a.shape)  # Prints the dimensions of the sparse matrix

(887060, 134712)


In [15]:
# Slice the sparse matrix (for example, the first 10 rows and 10 columns)
sliced_sparse_matrix = df_a[:10, :10]  # Adjust the slicing as needed

# Convert the sliced sparse matrix to a dense matrix
dense_sliced_matrix = sliced_sparse_matrix.toarray()

# Print the dense matrix
print(dense_sliced_matrix)

[[1. 1. 1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [16]:
df_a

<887060x134712 sparse array of type '<class 'numpy.float64'>'
	with 8171521 stored elements in Compressed Sparse Row format>

In [17]:
from scipy.sparse.linalg import svds
from scipy.linalg import svd
u, s, vt = svds(df_a, k=15)

In [21]:
print(u.shape)
print(s.shape)
print(vt.shape)

(887060, 15)
(15,)
(15, 134712)


In [22]:
import numpy as np

# Calculating the whole reconstructed matrix is too expensive for this dataset!
reconstructed_matrix = u @ np.diag(s) @ vt

MemoryError: Unable to allocate 890. GiB for an array with shape (887060, 134712) and data type float64

In [23]:
# To get the predicted ratings for playlist with index i (for example):
playlist_index = 0  # Replace with the desired playlist index

# Multiply the playlist row by the singular values
playlist_ratings = u[playlist_index, :] @ np.diag(s)

# Multiply the result by vt to get the predicted ratings for all tracks for that playlist
predicted_ratings = playlist_ratings @ vt

# Optionally, if you only want predicted ratings for a specific track (column)
track_index = 5  # Replace with the track index of interest
predicted_rating_for_track = predicted_ratings[track_index]

In [27]:
print(predicted_ratings)

[ 2.60932399e-01  1.66596602e-01  3.16699631e-01 ... -2.42845890e-07
  3.39510711e-12  1.49022853e-06]


In [30]:
import numpy as np

# Assuming u, s, vt are already obtained from svds

# To get the predicted ratings for playlist with index i
playlist_index = 0  # Replace with the desired playlist index

# Multiply the playlist row by the singular values
playlist_ratings = u[playlist_index, :] @ np.diag(s)

# Multiply the result by vt to get the predicted ratings for all tracks for that playlist
predicted_ratings = playlist_ratings @ vt

# Min-max normalization to [0, 1] for the predicted ratings of the current playlist
min_rating = np.min(predicted_ratings)
max_rating = np.max(predicted_ratings)

normalized_ratings = (predicted_ratings - min_rating) / (max_rating - min_rating)

# Optionally, if you want to get the normalized rating for a specific track
track_index = 5  # Replace with the track index of interest
normalized_rating_for_track = normalized_ratings[track_index]
print(normalized_ratings)

[0.8094066  0.56283816 0.95516717 ... 0.12739875 0.12739938 0.12740328]
